spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fastjk}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  mvc:
    validation:
      enabled: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      platform: postgres

server:
  port: 8080

app:
  client-id: ${GOOGLE_ID}
  secret: ${SECRET}